### ISSUE TITLE
mainpage is not showing a user icon

### ISSUE THREAD

**Issue by oberon2007** [linuxdeepin/dde-control-center#6]

**Comment by hualet** [comment]
@fasheng this problem is still there on arch-deepin ?

**Comment by oberon2007** [comment]
Still present, yes.

**Comment by hualet** [comment]
@jouyouyun how would that happen? we've fixed it, right ?

**Comment by oberon2007** [comment]
dde-c-c is still showing the default icon for me with the very latest packages, sorry ... ;)

**Comment by hualet** [comment]
hmm...we've encountered a similar situation and fixed the bug on mips architecture. @oberon2007 can you compile the latest commit of branch dev/2015 and see what it shows ?

**Comment by oberon2007** [comment]
Thank you @hualet ! I will try the latest commit a little later. Release 3.0.3 still has the issue in any case.

**Comment by oberon2007** [comment]
I just compiled https://github.com/linuxdeepin/dde-control-center/commit/7b1851bc6b79332de5b16329862427ebb0320634 and the issue has indeed been fixed :) Do we see a version bump, soon? Or otherwise @felixonmars would you consider updating the arch-deepin package?

**Comment by felixonmars** [comment]
Fixed now.
